### ISSUE TITLE
Build documentation for rocBLAS

### ISSUE THREAD

**Issue by gggh000** [ROCmSoftwarePlatform/rocBLAS#1177]
### What is the expected behavior
- build OK

### What actually happens
- build steps uncertain, causing failure.

### How to reproduce
- Follow the build steps outlined in 
https://rocmdocs.amd.com/en/latest/ROCm_Tools/rocblaswiki.html
### Environment
| Hardware | description |
|-----|-----|
| GPU | device string |
| CPU | device string |

| Software | version |
|-----|-----|
| ROCK | v0.0 |
| ROCR | v0.0 |
| HCC | v0.0 |
| Library | v0.0 |
it seem following steps are much straightforward specially for llvm toolchain as prerequisite:
llvm build and install: 
cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/opt/rocm-3.8.0/llvm/ -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang;lld;lldb;clang-tools-extra;compiler-rt" ../llvm
make install
in rocblas:
apt install gfortran libboost-all-dev -y
./install -id (install rocblas + dep)
./install -icd (install rocblas client + dep)

**Comment by daineAMD** [comment]
Hi @gggh000,
I'll be happy to look into your issue here, but I will need some clarification on some points:

•	What command line instruction are you using to attempt to build rocBLAS? Are you using `install.sh -idc`?
•	What failures are you seeing during the build?
•	What ROCm install are you using? You can get this with the command: `dpkg -l | grep rocm-dkms`
•	What GPU are you building on? You can get this with the command: `/opt/rocm/bin/rocm_agent_enumerator`

Also, the documentation you linked seems to be quite outdated, a more recent copy can be found [here](https://rocmdocs.amd.com/en/latest/ROCm_Libraries/ROCm_Libraries.html#rocblas), with more information available in the [rocBLAS User Guide](https://rocblas.readthedocs.io/en/latest/usermanual.html). The Building and Installing section may be more clear there. Alternatively you can browse through the [github wiki](https://github.com/ROCmSoftwarePlatform/rocBLAS/wiki) which should have the same information.

Thanks,
Daine

**Comment by daineAMD** [comment]
HI @gggh000,

I haven't heard back from you in about a week regarding this issue so I'll close it for now, I hope the updated documentation links helped. If you run into the issue again please go ahead and open another issue and address my questions and we can look into it again.

Thanks,
Daine
