### ISSUE TITLE
rocBLAS compilation fails with recent clang due to too-much __shared__ use.

### ISSUE THREAD

**Issue by Artem-B** [ROCmSoftwarePlatform/rocBLAS#1193]
This affects multiple source files. Here's one example:
https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/78203396eb36eedcd116713d9755a67c35e48d42/library/src/blas3/rocblas_symm.hpp#L58

```
    __shared__ T atile[TILE_NK][TILE_NK];    
    __shared__ T btile[TILE_NK][TILE_NK];
```

When the function is instantiated with TILE_NK=32 and T=rocblas_complex_num<double>,
the `atile` and `btile` consume 2*32*32*16 =32768 bytes.
If that would be the only instance present in the source file, that would be OK. 
However, during compilation we also instantiate the kernels for `rocblas_complex_num<float>` (that's 16K per instance) and for all permutations of `HERM` and `RIGHT` (thats up to 4x variants).

It used to work because clang was not checking the total amount of shared memory used within a single source file, however the [recent compiler change](https://github.com/llvm/llvm-project/commit/5e2facb922840bfd03eb116eaeead039df021275) by @rampitec added proper diags for such overuse and the compilation has started to fail.

One way to deal with this would be to instantiate each of the kernels in separate source files. Another option would be to pass the allowed shared memory as a kernel launch parameter.

**Comment by rampitec** [comment]
This sounds fishy. There was a bug causing overallocation with multiple kernels introduced by the [previous change](https://github.com/llvm/llvm-project/commit/8de4db697f2841748a5489d18d9fbcd130ae09bb), but it is fixed by the [change you have mentioned](https://github.com/llvm/llvm-project/commit/5e2facb922840bfd03eb116eaeead039df021275).

If that is still the case can I see compiler dumps? I've got one dump earlier with a similar report (rocblas_trsv_batched-hip-amdgcn-amd-amdhsa-gfx1030.ll) but I can build it with trunk compiler and max LDS usage is ~35K.

**Comment by rampitec** [comment]
Besides rocBLAS is tested in PSDB before changes are merged into internal branches. As far as I can see both changes are merged, PSDB is green including rocBLAS.

**Comment by Artem-B** [comment]
I see the issue with clang built from yesterday's llvm HEAD at https://github.com/llvm/llvm-project/commit/97d234935f1514af128277943f30efc469525371

The IR generated by the compiler before and after your changes is nearly identical (there are some logical ops changes in the code, but the rest is the same). Compilation is done with `--offload-arch=gfx900`. rocBLAS I'm using is from rocm-4.1.x branch, but AFAICT the source code didn't change. Let me try to reproduce the issue on a simple example.

The error I see:
```
error: local memory limit exceeded (98304) in _Z17symm_scale_kernelILi128ELi8EPKfPfEviiT1_T2_lil
error: local memory limit exceeded (106496) in _Z16symm_hemm_kernelILb0ELb0ELi32EPKfS1_PfEvbiiT2_T3_lilS4_lilT4_lil
error: local memory limit exceeded (106496) in _Z16symm_hemm_kernelILb0ELb1ELi32EPKfS1_PfEvbiiT2_T3_lilS4_lilT4_lil
error: local memory limit exceeded (98304) in _Z17symm_scale_kernelILi128ELi8EfPfEviiT1_T2_lil
error: local memory limit exceeded (106496) in _Z16symm_hemm_kernelILb0ELb0ELi32EfPKfPfEvbiiT2_T3_lilS4_lilT4_lil
error: local memory limit exceeded (106496) in _Z16symm_hemm_kernelILb0ELb1ELi32EfPKfPfEvbiiT2_T3_lilS4_lilT4_lil
error: local memory limit exceeded (98304) in _Z17symm_scale_kernelILi128ELi8EPKdPdEviiT1_T2_lil
error: local memory limit exceeded (114688) in _Z16symm_hemm_kernelILb0ELb0ELi32EPKdS1_PdEvbiiT2_T3_lilS4_lilT4_lil
error: local memory limit exceeded (114688) in _Z16symm_hemm_kernelILb0ELb1ELi32EPKdS1_PdEvbiiT2_T3_lilS4_lilT4_lil
error: local memory limit exceeded (98304) in _Z17symm_scale_kernelILi128ELi8EdPdEviiT1_T2_lil
error: local memory limit exceeded (114688) in _Z16symm_hemm_kernelILb0ELb0ELi32EdPKdPdEvbiiT2_T3_lilS4_lilT4_lil
error: local memory limit exceeded (114688) in _Z16symm_hemm_kernelILb0ELb1ELi32EdPKdPdEvbiiT2_T3_lilS4_lilT4_lil
error: local memory limit exceeded (98304) in _Z17symm_scale_kernelILi128ELi8EPK19rocblas_complex_numIfEPS1_EviiT1_T2_lil
error: local memory limit exceeded (98304) in _Z16symm_hemm_kernelILb0ELb0ELi32EPK19rocblas_complex_numIfES3_PS1_EvbiiT2_T3_lilS6_lilT4_lil
error: local memory limit exceeded (98304) in _Z16symm_hemm_kernelILb0ELb1ELi32EPK19rocblas_complex_numIfES3_PS1_EvbiiT2_T3_lilS6_lilT4_lil
error: local memory limit exceeded (98304) in _Z17symm_scale_kernelILi128ELi8E19rocblas_complex_numIfEPS1_EviiT1_T2_lil
error: local memory limit exceeded (98304) in _Z16symm_hemm_kernelILb0ELb0ELi32E19rocblas_complex_numIfEPKS1_PS1_EvbiiT2_T3_lilS6_lilT4_lil
error: local memory limit exceeded (98304) in _Z16symm_hemm_kernelILb0ELb1ELi32E19rocblas_complex_numIfEPKS1_PS1_EvbiiT2_T3_lilS6_lilT4_lil
error: local memory limit exceeded (98304) in _Z17symm_scale_kernelILi128ELi8EPK19rocblas_complex_numIdEPS1_EviiT1_T2_lil
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```
Here's the relevant IR with the data I see in my failing compilation:

```
; ModuleID = 'third_party/amdgpu/rocBLAS/library/src/blas3/rocblas_symm.cpp'
source_filename = "third_party/amdgpu/rocBLAS/library/src/blas3/rocblas_symm.cpp"
target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7"
target triple = "amdgcn-amd-amdhsa"

%class.rocblas_complex_num = type { float, float }
%class.rocblas_complex_num.2 = type { double, double }

$_ZZ25symm_hemm_mult_add_deviceILb0ELb0ELi32EfEvbiiT2_PKS0_iS2_iPS0_iE5atile = comdat any

$_ZZ25symm_hemm_mult_add_deviceILb0ELb0ELi32EfEvbiiT2_PKS0_iS2_iPS0_iE5btile = comdat any

$_ZZ25symm_hemm_mult_add_deviceILb0ELb1ELi32EfEvbiiT2_PKS0_iS2_iPS0_iE5atile = comdat any

$_ZZ25symm_hemm_mult_add_deviceILb0ELb1ELi32EfEvbiiT2_PKS0_iS2_iPS0_iE5btile = comdat any

$_ZZ25symm_hemm_mult_add_deviceILb0ELb0ELi32EdEvbiiT2_PKS0_iS2_iPS0_iE5atile = comdat any

$_ZZ25symm_hemm_mult_add_deviceILb0ELb0ELi32EdEvbiiT2_PKS0_iS2_iPS0_iE5btile = comdat any

$_ZZ25symm_hemm_mult_add_deviceILb0ELb1ELi32EdEvbiiT2_PKS0_iS2_iPS0_iE5atile = comdat any

$_ZZ25symm_hemm_mult_add_deviceILb0ELb1ELi32EdEvbiiT2_PKS0_iS2_iPS0_iE5btile = comdat any

$_ZZ25symm_hemm_mult_add_deviceILb0ELb0ELi32E19rocblas_complex_numIfEEvbiiT2_PKS2_iS4_iPS2_iE5atile = comdat any

$_ZZ25symm_hemm_mult_add_deviceILb0ELb0ELi32E19rocblas_complex_numIfEEvbiiT2_PKS2_iS4_iPS2_iE5btile = comdat any

$_ZZ25symm_hemm_mult_add_deviceILb0ELb1ELi32E19rocblas_complex_numIfEEvbiiT2_PKS2_iS4_iPS2_iE5atile = comdat any

$_ZZ25symm_hemm_mult_add_deviceILb0ELb1ELi32E19rocblas_complex_numIfEEvbiiT2_PKS2_iS4_iPS2_iE5btile = comdat any

$_ZZ25symm_hemm_mult_add_deviceILb0ELb0ELi32E19rocblas_complex_numIdEEvbiiT2_PKS2_iS4_iPS2_iE5atile = comdat any

$_ZZ25symm_hemm_mult_add_deviceILb0ELb0ELi32E19rocblas_complex_numIdEEvbiiT2_PKS2_iS4_iPS2_iE5btile = comdat any

$_ZZ25symm_hemm_mult_add_deviceILb0ELb1ELi32E19rocblas_complex_numIdEEvbiiT2_PKS2_iS4_iPS2_iE5atile = comdat any

$_ZZ25symm_hemm_mult_add_deviceILb0ELb1ELi32E19rocblas_complex_numIdEEvbiiT2_PKS2_iS4_iPS2_iE5btile = comdat any

@_ZZ25symm_hemm_mult_add_deviceILb0ELb0ELi32EfEvbiiT2_PKS0_iS2_iPS0_iE5atile = linkonce_odr hidden local_unnamed_addr addrspace(3) global [32 x [32 x float]] undef, comdat, align 16
@_ZZ25symm_hemm_mult_add_deviceILb0ELb0ELi32EfEvbiiT2_PKS0_iS2_iPS0_iE5btile = linkonce_odr hidden local_unnamed_addr addrspace(3) global [32 x [32 x float]] undef, comdat, align 16
@_ZZ25symm_hemm_mult_add_deviceILb0ELb1ELi32EfEvbiiT2_PKS0_iS2_iPS0_iE5atile = linkonce_odr hidden local_unnamed_addr addrspace(3) global [32 x [32 x float]] undef, comdat, align 16
@_ZZ25symm_hemm_mult_add_deviceILb0ELb1ELi32EfEvbiiT2_PKS0_iS2_iPS0_iE5btile = linkonce_odr hidden local_unnamed_addr addrspace(3) global [32 x [32 x float]] undef, comdat, align 16
@_ZZ25symm_hemm_mult_add_deviceILb0ELb0ELi32EdEvbiiT2_PKS0_iS2_iPS0_iE5atile = linkonce_odr hidden local_unnamed_addr addrspace(3) global [32 x [32 x double]] undef, comdat, align 16
@_ZZ25symm_hemm_mult_add_deviceILb0ELb0ELi32EdEvbiiT2_PKS0_iS2_iPS0_iE5btile = linkonce_odr hidden local_unnamed_addr addrspace(3) global [32 x [32 x double]] undef, comdat, align 16
@_ZZ25symm_hemm_mult_add_deviceILb0ELb1ELi32EdEvbiiT2_PKS0_iS2_iPS0_iE5atile = linkonce_odr hidden local_unnamed_addr addrspace(3) global [32 x [32 x double]] undef, comdat, align 16
@_ZZ25symm_hemm_mult_add_deviceILb0ELb1ELi32EdEvbiiT2_PKS0_iS2_iPS0_iE5btile = linkonce_odr hidden local_unnamed_addr addrspace(3) global [32 x [32 x double]] undef, comdat, align 16
@_ZZ25symm_hemm_mult_add_deviceILb0ELb0ELi32E19rocblas_complex_numIfEEvbiiT2_PKS2_iS4_iPS2_iE5atile = linkonce_odr hidden local_unnamed_addr addrspace(3) global [32 x [32 x %class.rocblas_complex_num]] undef, comdat, align 16
@_ZZ25symm_hemm_mult_add_deviceILb0ELb0ELi32E19rocblas_complex_numIfEEvbiiT2_PKS2_iS4_iPS2_iE5btile = linkonce_odr hidden local_unnamed_addr addrspace(3) global [32 x [32 x %class.rocblas_complex_num]] undef, comdat, align 16
@_ZZ25symm_hemm_mult_add_deviceILb0ELb1ELi32E19rocblas_complex_numIfEEvbiiT2_PKS2_iS4_iPS2_iE5atile = linkonce_odr hidden local_unnamed_addr addrspace(3) global [32 x [32 x %class.rocblas_complex_num]] undef, comdat, align 16
@_ZZ25symm_hemm_mult_add_deviceILb0ELb1ELi32E19rocblas_complex_numIfEEvbiiT2_PKS2_iS4_iPS2_iE5btile = linkonce_odr hidden local_unnamed_addr addrspace(3) global [32 x [32 x %class.rocblas_complex_num]] undef, comdat, align 16
@_ZZ25symm_hemm_mult_add_deviceILb0ELb0ELi32E19rocblas_complex_numIdEEvbiiT2_PKS2_iS4_iPS2_iE5atile = linkonce_odr hidden local_unnamed_addr addrspace(3) global [32 x [32 x %class.rocblas_complex_num.2]] undef, comdat, align 16
@_ZZ25symm_hemm_mult_add_deviceILb0ELb0ELi32E19rocblas_complex_numIdEEvbiiT2_PKS2_iS4_iPS2_iE5btile = linkonce_odr hidden local_unnamed_addr addrspace(3) global [32 x [32 x %class.rocblas_complex_num.2]] undef, comdat, align 16
@_ZZ25symm_hemm_mult_add_deviceILb0ELb1ELi32E19rocblas_complex_numIdEEvbiiT2_PKS2_iS4_iPS2_iE5atile = linkonce_odr hidden local_unnamed_addr addrspace(3) global [32 x [32 x %class.rocblas_complex_num.2]] undef, comdat, align 16
@_ZZ25symm_hemm_mult_add_deviceILb0ELb1ELi32E19rocblas_complex_numIdEEvbiiT2_PKS2_iS4_iPS2_iE5btile = linkonce_odr hidden local_unnamed_addr addrspace(3) global [32 x [32 x %class.rocblas_complex_num.2]] undef, comdat, align 16

```

**Comment by rampitec** [comment]
Could you attach a bitcode after -save-temps?

**Comment by Artem-B** [comment]
Here it is: 
[rocblas_symm-hip-amdgcn-amd-amdhsa-gfx900.bc.gz](https://github.com/ROCmSoftwarePlatform/rocBLAS/files/6587604/rocblas_symm-hip-amdgcn-amd-amdhsa-gfx900.bc.gz)

**Comment by rampitec** [comment]
Thanks. We must compile it differently. grep LDSByteSize after compilation:

; LDSByteSize: 0 bytes/workgroup (compile time only)
; LDSByteSize: 8192 bytes/workgroup (compile time only)
; LDSByteSize: 8192 bytes/workgroup (compile time only)
; LDSByteSize: 0 bytes/workgroup (compile time only)
; LDSByteSize: 8192 bytes/workgroup (compile time only)
; LDSByteSize: 8192 bytes/workgroup (compile time only)
; LDSByteSize: 0 bytes/workgroup (compile time only)
; LDSByteSize: 16384 bytes/workgroup (compile time only)
; LDSByteSize: 16384 bytes/workgroup (compile time only)
; LDSByteSize: 0 bytes/workgroup (compile time only)
; LDSByteSize: 16384 bytes/workgroup (compile time only)
; LDSByteSize: 16384 bytes/workgroup (compile time only)
; LDSByteSize: 0 bytes/workgroup (compile time only)
; LDSByteSize: 16384 bytes/workgroup (compile time only)
; LDSByteSize: 16384 bytes/workgroup (compile time only)
; LDSByteSize: 0 bytes/workgroup (compile time only)
; LDSByteSize: 16384 bytes/workgroup (compile time only)
; LDSByteSize: 16384 bytes/workgroup (compile time only)
; LDSByteSize: 0 bytes/workgroup (compile time only)
; LDSByteSize: 32768 bytes/workgroup (compile time only)
; LDSByteSize: 32768 bytes/workgroup (compile time only)
; LDSByteSize: 0 bytes/workgroup (compile time only)
; LDSByteSize: 32768 bytes/workgroup (compile time only)
; LDSByteSize: 32768 bytes/workgroup (compile time only)

**Comment by Artem-B** [comment]
Running upstream `llc` on the bitcode I've posted shows the same LDSByteSize for all entries.
How is it calculated?

```
$ bin/llc ~/tmp/rocblas_symm/rocblas_symm-hip-amdgcn-amd-amdhsa-gfx900.bc  -o - |grep LDSByteSize
error: local memory limit exceeded (147456) in _Z17symm_scale_kernelILi128ELi8EPKfPfEviiT1_T2_lil
; LDSByteSize: 147456 bytes/workgroup (compile time only)
error: local memory limit exceeded (147456) in _Z16symm_hemm_kernelILb0ELb0ELi32EPKfS1_PfEvbiiT2_T3_lilS4_lilT4_lil
; LDSByteSize: 147456 bytes/workgroup (compile time only)
```

Can you post the IR you've got in your build of rocblas_symm? I want to understand what's different between out builds.

**Comment by rampitec** [comment]
It traverses each function and collects everything a kernel uses. But thanks for the hint to run just llc on that dump (w/o any optimization). Now I see the same error!

**Comment by rampitec** [comment]
There really seems to be an error in the compiler, but it also seems your clang compilation does not run opt passes which triggers it.

What happens next is lower-module-lds pass collects LDS used from non-kernel functions and creates a single huge structure %llvm.amdgcn.module.lds.t used from all kernels because a non-entry function cannot define LDS use, it is statically allocated. I.e. the condition is triggered by the fact that these functions were not inlined (and there is no inlining happened in general).

While the bug needs to be fixed, the build also needs to be fixed to use opt passes.

**Comment by rampitec** [comment]
No, this is really a red herring. It does not work even w/o my patch. If there is no inlining that is the real LDS usage - 147456 bytes in each kernel. There must be something else to get the results reported - different per kernel LDS use and compilation with optimizations.

**Comment by Artem-B** [comment]
The build was done with -O3, though we also have tons of other options.
Considering that during full compilation I do get substantially different numbers in the limit errors, there are at least some passes applied past the `-emit-llvm` point that affect the outcome.

Can you post the IR you've got in your working build of rocblas_symm and the compiler options used? I'll try to figure out where my build deviates.

**Comment by rampitec** [comment]
That's the problem, I am using your IR since I am not building from source. Our compilation must deviate. I am then using two ways of compilation, both successful:

1) opt + llc

opt -march=amdgcn -mcpu=gfx900 -S -O3 -amdgpu-early-inline-all=true -amdgpu-function-calls=false rocblas_symm-hip-amdgcn-amd-amdhsa-gfx900.ll -o rocblas-symm.opt.ll
llc -march=amdgcn -mcpu=gfx900 -O3 rocblas-symm.opt.ll

2) clang:

clang -Xclang -fallow-half-arguments-and-returns --target=amdgcn-amd-amdhsa -mcpu=gfx900 -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -fhip-new-launch-api -O3 -Wno-unused-command-line-argument -Wall -Wextra -O3 -DNDEBUG -xhip -o test.o -c -x ir rocblas_symm-hip-amdgcn-amd-amdhsa-gfx900.ll

Actually what may help me if you could collect a dump before and after amdgpu-lower-module-lds. Pass this to clang:

-mllvm -print-after=amdgpu-lower-module-lds -mllvm -print-before=amdgpu-lower-module-lds

**Comment by Artem-B** [comment]
Interesting observation, my compilation succeeds with `-O1`, but not with `-O0` or `-O2` or `-O3`.
With `-O1`  `LDSByteSize` in the assembly do match the numbers you've reported.

AFAICT, in case of -O1, the `symm_hemm_mult_add_device` gets inlined into the kernel, but the loop is not unrolled. (which is probably what leads to the LDS size miscalculation). With -O2/O3, the symm_hemm_mult_add_device is heavily unrolled, but not inlined in to the kernel.

I suspect your build succeeds because it's not optimized aggressively enough. My guess is that adding a `#pragma unroll` to the symm_hemm_mult_add_device's outer loop would likely trigger the issue in your build, too.

**Comment by Artem-B** [comment]
Here's the before/after IR dump. [rocblas_symm.irdump.gz](https://github.com/ROCmSoftwarePlatform/rocBLAS/files/6587911/rocblas_symm.irdump.gz)

**Comment by rampitec** [comment]
I think it cannot build at -O0 because module LDS will be forced for every kernel and total it too big. This however has nothing to do with my changes and pre-existed. I believe someone has turned off forced inlining of functions defining LDS some time ago hence this would happen at -O0. This is not our scenario anyway.

Then heavy unrolling would prevent inlining, true, because function to inline is now too big for inlining. That would result in a similar issue.

However, all of that does not explain what happened after my patches because I did not mean to touch module (i.e. non-kernel functions') LDS, only the kernel LDS.

**Comment by Artem-B** [comment]
Considering that we can't reliably tell whether particular function is going to be inlined, is there a difference between a kernel and non-kernel functions in that regard? Depending on specific options, non-kernel function can be inlined into the kernel.

**Comment by rampitec** [comment]
Mistery solved, thanks for the dumps! This is really triggered by my patch, but that is [older patch](https://github.com/llvm/llvm-project/commit/748db5bfacf1f81f65e8c052459ed3eca6aa18c8).

These are all good news unfortunately. This patch fixes a real bug which was in the compiler since AMDGPULowerModuleLDSPass was introduced. The pass allows not to force inlining of functions defining LDS objects like it was before. Instead it creates a global LDS variable %llvm.amdgcn.module.lds holding all the LDS used by any non-kernel function and that variable is used by and available to every kernel in addition to the LDS defined by the kernel itself. Before this pass it was solved by forced inlining of such functions. Note this is unvoidable, only kernel (entry) functions can define statically allocated LDS, so we have to do it in compiler somehow. For instance OpenCL prohibits any LDS definitions in non-kernel functions specifically for that reason. Unfortunately CUDA does not.

This pass had a severe bug making an overlapped allocation of function's and kernel's LDS. Basically it was allocating both at address 0. As you can imagine functions where overwriting kernel's objects and if it did not happen for certain kernel that is a pure (and rare) luck. As a side effect kernel's allocation was smaller than needed. So the patch is correct and cannot be reverted. We are now having a correct behavior.

Let's explore the options:

1. We want to further improve the pass so that compiler will traverse CFG and only add LDS of reachable functions to the kernel LDS structure. This is a long haul though and will not help you in a near term.
2. Split the module.
3. Force inline of such functions.
4. Allocate LDS in a kernel and pass it to functions (an ideal option in fact).

**Comment by Artem-B** [comment]
I've also figured out a workaround. Adding `__attribute__((always_inline))` to symm_hemm_mult_add_device, appears to make build work again.

**Comment by rampitec** [comment]
> I've also figured out a workaround. Adding `__attribute__((always_inline))` to symm_hemm_mult_add_device, appears to make build work again.

Yes, see the explanation above! And thanks again for all the dumps.

**Comment by Artem-B** [comment]
OK, so let's keep this issue open, so rocBLAS folks can refactor the kernels.
Please CC me on LLVM review when you have it, so I know when it lands.

And thank you for your help debugging the issue.

**Comment by rampitec** [comment]
> Please CC me on LLVM review when you have it, so I know when it lands.

It's currently on Mahesha's plate, but I am not sure who will end up writing the actual transformation. It is somewhat tricky to make such function working beeing called from different kernels (static addresses shall be the same) and with indirect calls. The latter is the real reason to stop forced inlining by the compiler.

**Comment by TorreZuk** [comment]
I will take this issue and make code changes for the failing kernels as I had already reported an internal ticket.  Other kernels appear to be affected so will have to review them all to determine if a consistent solution can be applied.   I can update this issue when changes are complete.

**Comment by TorreZuk** [comment]
Changes for the explicit inlining workaround have been merged to master and should be in the 4.4 release in commit 4dabf43e77f56ac460898e60aca5fb00267fa464.    Further changes may be required as the llvm evolves but perhaps we can close this issue now, @Artem-B ?

**Comment by rampitec** [comment]
Note that since https://reviews.llvm.org/rG80fd5fa5269ce102b3126d2de49970e3af6719d5 it shall work without inlining too.

**Comment by TorreZuk** [comment]
Thanks @rampitec , that is good to know.   We never know what will end up being the frozen version of llvm/clang officially used for a rocBLAS release in the future so hopefully that change will be used soon and no further modifications are required.

**Comment by TorreZuk** [comment]
Still using explicit inlining in rocblas sub kernel function calls and working fine.  Closing issue as no further changes made.
