### ISSUE TITLE
Errors while installing Library Dependencies For rocBLAS

### ISSUE THREAD

**Issue by srilekhainkulu99** [ROCmSoftwarePlatform/rocBLAS#1258]
Below file holds the errors while installing library dependencies in order to use rocblas-bench.
OS Version - Ubuntu 18.04
command used to install library dependencies - ./install.sh -c
Can you please provide a solution for this?

[errors list.txt](https://github.com/ROCmSoftwarePlatform/rocBLAS/files/9207752/errors.list.txt)

**Comment by rkamd** [comment]
@srilekhainkulu99 ,
The error seems to indicate that google test is installed during the build process. In order to install the dependencies properly to build the client programs, I would suggest using '-d' flag. 
For example 
```
  ./install -dc
``` 
Also you can pass architecture specific flag to speed-up the build process. 
```
./install.sh -dc -agfx908:xnack-
```

**Comment by rkamd** [comment]
@srilekhainkulu99 ,
If the suggested flag resolved the problem, Please close this issue. Thanks.
