### ISSUE TITLE
[Issue]: Missing input file and output command on rocBLAS documentation

### ISSUE THREAD

**Issue by afanfa** [ROCmSoftwarePlatform/rocBLAS#1382]
### Problem Description

The documentation at the following link https://rocm.docs.amd.com/projects/rocBLAS/en/latest/Programmers_Guide.html#rocblas-gemm-tune has an example input file and expected output.

### Operating System

N/A

### CPU

N/A

### GPU

N/A

### ROCm Version

5.7.1

### ROCm Component

rocBLAS documentation

### Output of /opt/rocm/bin/rocminfo --support

N/A

**Comment by amcamd** [comment]
@afanfa Do you have a question? I do not see a question in your GitHub issue 1382.

**Comment by amcamd** [comment]
Added correction to  https://rocm.docs.amd.com/projects/rocBLAS/en/latest/Programmers_Guide.html#rocblas-gemm-tune for path of example_user_driven_tuning.cpp. The correct path is:
`rocBLAS/clients/samples/example_user_driven_tuning.cpp`

**Comment by daineAMD** [comment]
@afanfa It's not clear to me what you're asking in this issue. I took a look at the documentation you linked and made a small amendment at https://github.com/ROCm/rocBLAS/commit/036b6629f7277d5db90e24d872c74a555764435f.
Please let me know if you're still seeing an issue, otherwise I'll close this issue next week.

Thanks,
Daine

**Comment by afanfa** [comment]
The correction made by @amcamd was satisfactory. There were entire parts missing from that page. Closing this issue.
