### ISSUE TITLE
roc::rocblas target and C++ compilers

### ISSUE THREAD

**Issue by jszuppe** [ROCmSoftwarePlatform/rocBLAS#143]
If you use `roc::rocblas` target (defined in `rocblas-config.cmake`) in your cmake script to link to rocBLAS, you have to use `hcc` as you C++ compiler. I think this happens because `hip::hip_hcc` in [here](https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/develop/library/src/CMakeLists.txt#L127) is marked `PUBLIC`, which means its dependencies are transitive and compilation options are passed to `roc::rocblas` (I understand that this is so the HIP dirs are included). Unfortunately, some of those options work only with `hcc` compiler.

I just want to know if it's supposed to be that way (`roc::rocblas` works with `hcc`, if you want to use different compiler use `rocblas_INCLUDE_DIRS` , `rocblas_LIB_INSTALL_DIR`,  and `-lrocblas`), or if this is work-in-progress.

**Comment by kknox** [comment]
Hi @jszuppe, good to see you again.  Thanks for the feedback. 

I made the `hip::hip_hcc` dependency public because we expose the hip header files through the [rocblas header files](https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/develop/library/include/rocblas-types.h#L16).  However, I see your point that the public compiler flags is inconvenient.  I don't want to drag a compiler dependency forward.

Ultimately, I think the real fix is going to be to split the hip exported targets, such that I can make the hip header files public without making the link flags public.  That will require refactoring up in the hip layer.  That may take some time.

Until then, I can probably hide the `hip::hip_hcc` dependency privately and export the hip header files publicly from our config targets.

**Comment by jszuppe** [comment]
> I made the hip::hip_hcc dependency public because we expose the hip header files through the rocblas header files. 

Yes, you documented why you did it. I just wasn't sure if the mentioned consequence of that was intended or not. I assumed it might be intended since you dropped support for `nvcc`, and maybe want to push people to use `hcc` as C++ compiler on ROCm.

> Ultimately, I think the real fix is going to be to split the hip exported targets, such that I can make the hip header files public without making the link flags public. That will require refactoring up in the hip layer. That may take some time.

I agree it should be addressed in the hip layer. 

> Until then, I can probably hide the hip::hip_hcc dependency privately and export the hip header files publicly from our config targets.

I have the same problem with project I'm working on and I was wondering about the best approach to that. Right now, I just pushed it to private. Mentioned project works both on ROCm and CUDA platforms, 
they have to explicitly link they targets to CUDA libraries anyway, I figured they can tolerate doing the same for HIP.

**Comment by kknox** [comment]
I think this is fixed; will close it out in a week or so if I don't hear a confirm/deny.  Thx.
